USE [master]
GO

/****** Object:  Database [Сакалов Квалиф]    Script Date: 05.07.2023 12:10:18 ******/
CREATE DATABASE [Сакалов Квалиф]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Сакалов Квалиф', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Сакалов Квалиф.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Сакалов Квалиф_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Сакалов Квалиф_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Сакалов Квалиф] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Сакалов Квалиф].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Сакалов Квалиф] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET ARITHABORT OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Сакалов Квалиф] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Сакалов Квалиф] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Сакалов Квалиф] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Сакалов Квалиф] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Сакалов Квалиф] SET  MULTI_USER 
GO

ALTER DATABASE [Сакалов Квалиф] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Сакалов Квалиф] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Сакалов Квалиф] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Сакалов Квалиф] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Сакалов Квалиф] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Сакалов Квалиф] SET  READ_WRITE 
GO

